### PR TITLE
Release as a universal wheel

### PR DESCRIPTION
**Pull request by adamchainz**
By releasing as a [Python wheel](http://pythonwheels.com/) as well as a source distribution, you can speed up end user’s installs. After merging this command, to release you just need to run `python setup.py clean sdist bdist_wheel upload`.

### CODE REVIEW

**Comment by repeatedly** [comment]
I'm not familiar with wheel package format.
Should we release fluent-logger-python with egg and wheel?
Or can we switch to only wheel?

**Comment by methane** [comment]
egg is no longer used.
sdist (.tar.gz) + bdist_wheel (.whl) is current standard.

**Comment by repeatedly** [comment]
I see. I will release whl package at the same time.

**Comment by adamchainz** [comment]
👍 👍 🎡

**Pull request merged**
